#! /usr/bin/env python3

import os
import signal
import time
import psutil
import json

pids = json.loads(open('pids.log').read())

psutil.Process(pids['scv_pid']).kill()

# psutil's kill doesn't quite work for forks
os.kill(pids['cc_pid'], signal.SIGTERM)

time.sleep(1)

os.system('rm -rf pids.log core_keys.log *_data')
