#! /usr/bin/env python

# Start services necessary to test the core.
import os
import subprocess
import time
import requests
import json
import base64
import gzip
import pymongo


def add_manager():
    reply = requests.post('https://127.0.0.1:8980/managers',
                          data=json.dumps({'email': 'test_user@gmail.com',
                                           'password': 'test_pass',
                                           'role': 'admin',
                                           'weight': 1}),
                          verify=False)
    assert reply.status_code == 200


def add_engine_token(manager_token):
    headers = {'Authorization': manager_token}
    reply = requests.post('https://127.0.0.1:8980/engines/keys',
                          data=json.dumps({"engine": "openmm",
                                           "description": "hehehe"}),
                          headers=headers,
                          verify=False)
    assert reply.status_code == 200
    return reply.json()['key']


def add_donor():
    reply = requests.post('https://127.0.0.1:8980/donors',
                          data=json.dumps({'username': 'test_donor',
                                           'email': 'test_donor@gmail.com',
                                           'password': 'test_donor_pass'}),
                          verify=False)
    assert reply.status_code == 200
    return reply.json()['token']


def auth_manager():
    reply = requests.post('https://127.0.0.1:8980/managers/auth',
                          data=json.dumps({'email': 'test_user@gmail.com',
                                           'password': 'test_pass'}),
                          verify=False)
    return json.loads(reply.content.decode())['token']


def post_target(auth_token, stage='private'):
    message = json.dumps({'engines': ['openmm'],
                          'options': {
                              'description': 'foo',
                              'steps_per_frame': 10000
                          },
                          'stage': stage,
                          'weight': 1,
                          })
    reply = requests.post('https://127.0.0.1:8980/targets',
                          headers={'Authorization': auth_token},
                          verify=False,
                          data=message,
                          )
    return json.loads(reply.content.decode())['target_id']


def post_streams(target_id, files, auth_token):
    message = json.dumps({'target_id': target_id,
                          'files': files})
    reply = requests.post('https://127.0.0.1:8980/streams',
                          headers={'Authorization': auth_token},
                          verify=False,
                          data=message
                          )
    assert reply.status_code == 200
    return json.loads(reply.content.decode())['stream_id']

if __name__ == '__main__':
    # if a pids.log exists, that means we need to do some cleanup!
    mdb = pymongo.MongoClient()
    for db_name in mdb.database_names():
        mdb.drop_database(db_name)
    if os.path.exists('pids.log'):
        stop_path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                                 'stop_services')
        os.system(stop_path)
    cc_path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                           '..', '..', 'cc')
    ws_path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                           '..', '..', 'scv')
    pid2 = subprocess.Popen(ws_path, stdout=subprocess.PIPE, shell=True,
                            preexec_fn=lambda: os.setpgid(0, 0))
    time.sleep(1)
    pid1 = subprocess.Popen(cc_path, stdout=subprocess.PIPE, shell=True,
                            preexec_fn=lambda: os.setpgid(0, 0))
    time.sleep(1)
    with open('pids.log', 'w') as log:
        log.write(str(pid1.pid))
        log.write(' ')
        log.write(str(pid2.pid))

    add_manager()

    token = auth_manager()
    core_key = add_engine_token(token)
    # post a public target
    target_id = post_target(token, stage='public')
    state_url = 'http://www.stanford.edu/~yutongz/state.xml.gz'
    system_url = 'http://www.stanford.edu/~yutongz/system.xml.gz'
    integrator_url = 'http://www.stanford.edu/~yutongz/integrator.xml.gz'
    state_gz = requests.get(state_url).content
    system_gz = requests.get(system_url).content
    integrator_gz = requests.get(integrator_url).content
    encoded_system = base64.b64encode(system_gz).decode()
    encoded_intg = base64.b64encode(integrator_gz).decode()
    encoded_state = base64.b64encode(state_gz).decode()
    files = {
        'system.xml.gz.b64': encoded_system,
        'state.xml.gz.b64': encoded_state,
        'integrator.xml.gz.b64': encoded_intg
    }
    for i in range(20):
        post_streams(target_id, files, token)

    target_id = post_target(token)
    post_streams(target_id, files, token)
    donor_token = add_donor()

    # post a private target
    with open('target_ids.log', 'w') as log:
        log.write(str(target_id))
    with open('core_keys.log', 'w') as log:
        log.write(str(core_key))
    with open('donor_tokens.log', 'w') as log:
        log.write(str(donor_token))
