#! /usr/bin/env python

import os
import signal

pids = open('pids.log').read().split(' ')

for pid in pids:
    try:
        os.killpg(int(pid), signal.SIGTERM)
    except Exception:
        pass

os.system('rm -rf aof_* streams targets')
